### ISSUE TITLE
[FEATURE] After closing a solution refresh the Recent items

### ISSUE THREAD

**Issue by MagicAndre1981** [luminous-software/start-page-plus-64-bit#13]
([private Issue 5](https://github.com/yannduran/start-page-plus-64-bit/issues/5))

**Is your feature request related to a problem? Please describe.**
After a solution is closed, the recent item list is not updated.

**Describe the solution you'd like**

After a solution is closed, the recent item list is not updated and the _Refresh_ should be called.

Same issue as already reported for the [VS2019 version](https://github.com/luminous-software/start-page-plus-64-bit/issues/26)

**Comment by yannduran** [comment]
Thanks for reminding me. I had planned on fixing that, but forgot about it. There are some actions that don't update the list at the moment, but I'm not sure I can refresh the list after a solution close. Maybe. I'll have to have a look at it. Manually refreshing the list after closing a solution works though, right?

These issues that you've added for me will be very helpful to stop things like that falling through the cracks.

**Comment by yannduran** [comment]
Implemented in v0.21

**Comment by MagicAndre1981** [comment]
this is not working for me in v0.21. I still had to click Refresh after solution close.

**Comment by yannduran** [comment]
Hmmm, it worked for me. Or at least it seemed to. What I did was:
- open a solution
- minimise one of more time groups on SP+
- close the solution
- the groups were expanded on SP+ (that told me that a refresh had been done)

What did you do when it didn't work for you? I kind of need more than "it didn't work" to be able to reproduce it.

**Comment by MagicAndre1981** [comment]
the times were wrong. the opened/closed solution didn't show up as "today", but do if I click on refresh.

**Comment by yannduran** [comment]
OK, I'll look into it tomorrow (probably).

**Comment by MagicAndre1981** [comment]
I check the steps and group is NOT expanded until I manually click on Refresh here it is expanded.

**Comment by yannduran** [comment]
André, please don't report a bug in a closed issue. You need to create a bug report instead. Otherwise it's hard for me to track things properly. I've only just realised.

I've created a [bug report](https://github.com/luminous-software/start-page-plus-64-bit/issues/33) for you & transferred our conversion into it.
