### ISSUE TITLE
[FEATURE] Add option to show/hide csproj files in recent items list

### ISSUE THREAD

**Issue by MagicAndre1981** [luminous-software/start-page-plus-64-bit#15]
### Installed product versions
- Visual Studio: 2019 16.8.2
- This extension: 1.0.1

### Description

add an option to exclude csproj files from showing under recent items

### Steps to recreate / Current behavior
1. open sln
2. add an existing csproj to the sln 
3. close sln
4. the csproj now show up on recent

### Expected behavior

recent items should not show csproj because I always open the sln for the project. For people who like the old way an option should be added to control which files get added to `recent items`.

**Comment by yannduran** [comment]
Implemented in v0.21
