### ISSUE TITLE
[FEATURE] Add tooltips for News Items

### ISSUE THREAD

**Issue by TonyGravagno** [luminous-software/start-page-plus-64-bit#16]
I would like to see the URLs with mouseover on news items. I'd like to be able to copy the links with  without opening the page. I feel more comfortable knowing where a link is going, a little vulnerable just clicking links, for all of the reasons why we know just clicking links isn't healthy. 

VS2019 with spp 0.14.3
Looking forward to other changes already noted for News tab. Thanks!

**Comment by yannduran** [comment]
@TonyGravagno I don't know if you're still using **_Start Page+_** anymore, but I just wanted you to know that a feature you requested, in the 2019 version of **_Start Page+_**, is coming up in the next sprint (`v0.22`) of the 64-bit version.

I've added more than just the link that you requested. I've also added the title & the full description, and the link, as requested. I'll be interested to see what you think of the results.

![image](https://user-images.githubusercontent.com/2031126/236897426-408624bd-bf0a-4cba-abcb-cf6757074297.png)

The first time you hover over an item, it'll take 2000 milliseconds to display, but as you then move from item to item the tooltip will be immediate. It you stay hovering over an item, the tooltip will disappear in 70000 milliseconds.

**Comment by yannduran** [comment]
Implemented in `v0.22`

**Comment by TonyGravagno** [comment]
Yann - Sincere thanks to you. After so many years dedicated to Visual Studio ( Pro, Ultimate, Enterprise, etc ) I shifted technology focus and have transitioned to Visual Studio Code (why do they name products like this? :smile: ). Best to you.

**Comment by yannduran** [comment]
Thanks Tony!
