### ISSUE TITLE
The solution date

### ISSUE THREAD

**Issue by TBOpen** [luminous-software/start-page-plus-64-bit#27]
### Installed product versions
- Visual Studio: 2019
- This extension: 1.0.1

### Description
Sometimes I startup VS2019 and my project/solution I'm working on isn't at the top anymore, I scroll down and it's way down with some date back in the future, like today says 4/12/21 but I worked on it a few days ago as was up at the top.

### Steps to recreate
It does it randomly

**Comment by yannduran** [comment]
Please let me know if this type of thing starts happening in the 64-bit version of Start Page+ though I agree with André that it's more likely to be something related to Visual Studio itself.

I'll close this for now, but please feel free to open it again if it does cause your a problem.
