### ISSUE TITLE
[FEATURE] Add ARM64 support

### ISSUE THREAD

**Issue by MagicAndre1981** [luminous-software/start-page-plus-64-bit#3]
**Describe the solution you'd like**

Since Visual Studio 2022 17.4, there is an [ARM64 version of VS2022](https://learn.microsoft.com/en-us/visualstudio/install/visual-studio-on-arm-devices?view=vs-2022) available and [Microsoft provides an ARM64 development system](https://learn.microsoft.com/en-us/windows/arm/dev-kit/). For those people who would like Start Page+ instead of the Start Window, you should consider to add [ARM64 support](https://devblogs.microsoft.com/visualstudio/now-introducing-arm64-support-for-vs-extensions/)

Compiling as AnyCPU and adding the ARM64 entry to [the manifest](https://github.com/luminous-software/start-page-plus-64-bit/blob/eb79537e79a146d6564bf279bc6fe25eb672e578/src/vsix/source.extension.vsixmanifest#L17) provides the support:

```xml
<InstallationTarget Id="Microsoft.VisualStudio.Community" Version="[17.4,18.0)">
   <ProductArchitecture>arm64</ProductArchitecture>
</InstallationTarget>
```

**Describe alternatives you've considered**

ARM64 users have to wait until Microsoft releases their [Welcome Page](https://devblogs.microsoft.com/visualstudio/welcome-experience/) in a future VS2022 update to the public, without having to enable it as preview feature.

**Comment by yannduran** [comment]
I hadn't even considered this, so thanks for the heads-up. If it's that easy to enable support, I don't see why not.

**Comment by yannduran** [comment]
Btw, for something as simple as this, you're welcome to add a pull request if you feel like it.

**Comment by MagicAndre1981** [comment]
> Btw, for something as simple as this, you're welcome to add a pull request if you feel like it.

done with #8
