### ISSUE TITLE
[BUG] Recent list shows no path, only project name 

### ISSUE THREAD

**Issue by MagicAndre1981** [luminous-software/start-page-plus-64-bit#6]
**Describe the bug**

In the list of recent projects, I see no path names. I only see the project name

**To Reproduce**

1. Open and close several solutions
2. Click on 'Refresh' to see the last used projects
3. look on the list and all projects have no path 

**Expected behavior**

List of projects with path, as I use several working copies of the same project from different branches, so the path name is very important for me.

**Screenshots**

![image](https://user-images.githubusercontent.com/8274816/233639529-10d0a82c-8553-4547-82cf-f3d0aeceae87.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 11 22621
 - Version [e.g. 22] VS 2022 17.4 LTSC

**Comment by yannduran** [comment]
You're absolutely right! I did notice that, but forgot about it. Thanks!

**Comment by MagicAndre1981** [comment]
ok, found it. There setting that controls if paths are shown or not and the [setting is disabled by default](https://github.com/luminous-software/start-page-plus-64-bit/blob/eb79537e79a146d6564bf279bc6fe25eb672e578/src/vsix/Options/Pages/PageConstants.cs#L64). So consider setting it to true by default.

![image](https://user-images.githubusercontent.com/8274816/233714686-6f7e909d-22d1-4666-a172-24b7297a97d3.png)

After changing the setting I had to restart VS, only closing/re opening Start Page+ was not enough.

**Comment by yannduran** [comment]
Good catch! Thanks André
